######################################################################
# Automatically generated by qmake (3.0) Sat Sep 19 12:09:07 2020
######################################################################

TEMPLATE = app
TARGET = clock
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += clock_widget.h
SOURCES += clock.cpp clock_widget.cpp
